language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install

script: phpunit --coverage-text -c ./tests/phpunit.xml

notifications:
  email:
    - polidogs@gmail.com
